config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root to: "books#index"
  get "/search", to: "books#search"
  get "/buy/:book_id", to: "orders#buy", as: "buy"
  get "/success", to: "orders#success", as: "success"
  get "/cancel", to: "orders#cancel", as: "cancel"
  get '/add_to_cart/:book_id', to: "carts#add_to_cart", as: "add_to_cart"
  get '/buy', to: "carts#buy", as: 'checkout_buy'
  get '/cart', to: "carts#cart", as: "cart"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy

    def full_name
        return "#{first_name} #{last_name}"
    end
end

app/models/book.rb
class Book < ApplicationRecord
    resourcify
    belongs_to :user

    has_many :liked_books
    has_many :likers, through: :liked_books, source: :user

    has_many :favourited_books
    has_many :favouriters, through: :favourited_books, source: :user
    
    belongs_to :author
    has_many :book_genres, dependent: :destroy
    has_many :genres, through: :book_genres

    has_many :book_carts, dependent: :destroy
    has_many :carts, through: :book_carts

    has_one_attached :cover, dependent: :purge

    validates :title, presence: { message: "Please provide a title" }
    validates :date_published, presence: { message: "Please set a publication date" }
    validate :past_date

    def past_date
        if date_published >= Date.today
            errors.add(:date_published, "Date published must be in the past")
        end
    end
end

app/models/book_cart.rb
class BookCart < ApplicationRecord
  belongs_to :book
  belongs_to :cart
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  validate :check_that_no_cart_for_that_user_exists
  has_many :book_carts, dependent: :destroy
  has_many :books, through: :book_carts

  def check_that_no_cart_for_that_user_exists
    uncompleted_carts = Cart.where(user_id: user, completed: false)
    if uncompleted_carts.count > 0
      errors.add(:base, "ya boi can't make any more carts")
    end
  end
end

app/models/favourited_book.rb
class FavouritedBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/foo.rb
class Foo < ApplicationRecord
  belongs_to :reviewer
  belongs_to :reviewee
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :book_genres, dependent: :destroy
    has_many :books, through: :book_genres
end

app/models/liked_book.rb
class LikedBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :person_who_reviewed, class_name: "User", foreign_key: :reviewer_id
  belongs_to :reviewee, class_name: "User"
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role

  # reviews a user has created
  has_many :reviews_made, class_name: "Review", foreign_key: :reviewer_id
  # reviews of a user
  has_many :reviews_of, class_name: "Review", foreign_key: :reviewee_id




  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts

  #owned 
  has_many :books
  #liked
  has_many :liked_books #joining table
  has_many :liked, through: :liked_books, source: :book #method relationship
  #fav'd
  has_many :favourited_books
  has_many :favourited, through: :favourited_books, source: :book

  def set_role
    self.add_role(:user) if self.roles.blank?
  end

  def cart 
    return Cart.find_by(user_id: id, completed: false) || Cart.create(user_id: id, completed: false, price: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :forbidden

    private

    def forbidden
        flash[:alert] = "You are not authorised to perform that action!"
        redirect_to(request.referrer || root_path)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_auth, except: [:search]
  before_action :set_authors_and_genres, only: [:new, :edit, :create]
  before_action :set_book, only: [:update, :edit, :show, :destroy]

  def search
    # exact search
    # @books = Book.where(title: "a")

    # like search
    case params[:type]
    when "genre"
    when "publisher"
    when "author"
      @books = []
      authors = Author.where("first_name LIKE ?", "%#{params[:query]}%").or(Author.where("last_name LIKE ?", "%#{params[:query]}%"))
      authors.each do |author|
        author.books.each do |book|
          @books << book
        end
      end
    when "title"
      @books = Book.where("title LIKE ?", "%#{params[:query]}%")
    end
      render "index"
  end

  def new
    @book = Book.new
  end

  def index
    @books = Book.order(title: :asc)
  end

  def create
    @book = Book.new(book_params)
    begin
      @book.save!
      redirect_to @book
    rescue
      flash.now[:errors] = @book.errors.messages.values.flatten
      render 'new'
    end
  end

  def update
    @book.update(book_params)
    redirect_to @book
  end

  def edit
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def show
  end

  private

  def book_params
    params.require(:book).permit(:title, :publisher, :date_published, :cover, :author_id, genre_ids: [])
  end

  def set_authors_and_genres
    @authors = Author.order(:last_name)
    @genres = Genre.order(:name)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def check_auth
    authorize Book
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    # GET /add_to_cart
    def add_to_cart
        book = Book.find(params[:book_id])
        current_user.cart.books << book
        flash[:notice] = "Book added to cart"
        redirect_to book
    end

    def cart
        @books = current_user.cart.books
    end

    def buy
        Stripe.api_key = "sk_test_51JtOgyFfeA45SmyCiW7WGpTRDRHovWV0F6D4oOxHDhVGowTHvtMzxOlHeyawRE5rJyVlkEctm0RhwQ3S07Ohtv1z000usO3RYs"
        
        line_items = current_user.cart.books.map do |book|
            {
            price_data: {
                currency: 'aud',
                product_data: {
                    name: book.title,
                },
                unit_amount: book.price,
                },
                quantity: 1, 
            }
        end
  
        session = Stripe::Checkout::Session.create({
            payment_method_types: ['card'],
            line_items: line_items,
            mode: 'payment',
            # These placeholder URLs will be replaced in a following step.
            #www.blah.com/success?session_id={CHECKOUT_SESSION_ID}"
            success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url: cancel_url,
          })
  
          redirect_to session.url
      end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    # GET /buy
    def buy
      Stripe.api_key = "sk_test_51JtOgyFfeA45SmyCiW7WGpTRDRHovWV0F6D4oOxHDhVGowTHvtMzxOlHeyawRE5rJyVlkEctm0RhwQ3S07Ohtv1z000usO3RYs"
      
      book = Book.find(params[:book_id])

      line_item = {
        price_data: {
          currency: 'aud',
          product_data: {
            name: book.title,
          },
          unit_amount: book.price,
        },
        quantity: 1,
      }

      session = Stripe::Checkout::Session.create({
          payment_method_types: ['card'],
          line_items: [line_item],
          mode: 'payment',
          # These placeholder URLs will be replaced in a following step.
          #www.blah.com/success?session_id={CHECKOUT_SESSION_ID}"
          success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
          cancel_url: cancel_url,
        })

        redirect_to session.url
    end

    def success
    end

    def cancel
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book do |f| %>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :cover %>
        <%= f.file_field :cover %>
    </p>
    <p>
        <%= f.label :author_id %>
        <%= f.collection_select :author_id, @authors, :id, :full_name %>
    </p>
    <p>
        <%= f.label :publisher %>
        <%= f.text_field :publisher %>
    </p>
    <p>
        <%= f.label :date_published %>
        <%= f.date_field :date_published %>
    </p>
    <p>
        <%= f.label :genres %>
        <%= f.collection_check_boxes :genre_ids, @genres, :id, :name %>
    </p>
    <p>
        <%= f.submit caption %>
    </p>
<% end %>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form', caption: "Save Changes" %>

app/views/books/index.html.erb
<h1>Books</h1>

<% if policy(Book).new? %>
    <p><%= link_to "New Book", new_book_path %></p>
<% end %>

<table>
    <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
    </tr>
    <% @books.each do |book| %>
        <tr>
            <td><%= cl_image_tag book.cover.key, crop: :scale, width: 50, cloud_name: 'flynnwebdev' if book.cover.attached? %></td>
            <td><%= link_to book.title, book %></td>
            <td><%= book.author.full_name %></td>
        </tr>
    <% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', caption: "Do It!" %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h3>By <%= @book.author.full_name %></h3>
<% if @book.cover.attached? %>
    <%= image_tag @book.cover, width: 150 %>
<% end %>
<h5>Genres: <%= @book.genres.map { |g| g.name }.join(", ") %></h5>
<p>Publisher: <%= @book.publisher %></p>
<p>Date Published: <%= @book.date_published %></p>
<p>
    <%= link_to "<< Back to book list", books_path %>
    <%= link_to "BUY NOW!", buy_path(@book.id) %>
    |
    <%= link_to "Add To Cart", add_to_cart_path(@book.id) %>
    <% if policy(@book).update? %>
        |
        <%= link_to "Edit", edit_book_path(@book) %>
    <% end %>
    <% if policy(@book).destroy? %>
        |
        <%= link_to "Delete", @book, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/carts/cart.html.erb
<h1>Your cart</h1>

<table>
    <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
    </tr>
    <% @books.each do |book| %>
        <tr>
            <td><%= cl_image_tag book.cover.key, crop: :scale, width: 50, cloud_name: 'flynnwebdev' if book.cover.attached? %></td>
            <td><%= link_to book.title, book %></td>
            <td><%= book.author.full_name %></td>
        </tr>
    <% end %>
</table>

<%= link_to "Buy All!", checkout_buy_path %>